### ISSUE TITLE
The DOM4 Elements collection

### ISSUE THREAD

**Issue by simevidas** [eorroe/NodeList.js#1]
Have you seen the recently specced Elements collection? https://twitter.com/openwebdaily/status/593439888080502787

It adds the Array methods and is intended as a replacement for NodeList. Maybe it would make sense to refactor your code so that it becomes “Elements on steroids”, with an Elements polyfill as a basis.

**Comment by eorroe** [comment]
Well at the bottom I said it was a horribly written repository `readme`, but I've been thinking of figuring out a replacement for `NodeList`. I'm not sure what you mean, should I make `NodeList` completely extend `Array` so it can have all methods like `push`, `pop` etc? can you elaborate a bit and `query` and `queryAll` isn't that the equivalent of calling `querySelector` and `querySelectorAll` on each `Node` which is what I already do? My belief is that `NodeList` should be able to do anything a `Node` can do but just on each `Node` of the `NodeList` and more like the `Array` methods and other methods.

**Comment by simevidas** [comment]
From the tone of the spec text, it seems that the intention is to deprecate NodeList in favor of Elements. NodeList could very well become legacy in the near future. Therefore, it might make sense to use Elements instead of NodeList as a basis for your dynamic extensions. 

So, at the core there would be an Elements polyfill which would implement the interfaces from the latest DOM spec. Then, you can build on top of that polyfill by adding your extensions.

Just an idea, though :)

**Comment by eorroe** [comment]
I don't like it, `NodeList` are here and everywhere. I believe `jQuery` uses it a lot. Deprecating `NodeList` would be hard or take a while IMO. I think extending `NodeList` would be the right answer. I mean my idea wouldn't hurt no compatibility issues because `NodeList` don't actually do anything. They don't have any functionality but to store live nodes. So I'm not really feeling `Elements` collection, I'd prefer extending `NodeList` don't you? I just need help making this better like should `NodeList` be able to have every `Array` method? And what other methods? So imagine my implementation of `NodeList` was natively implemented, no website would break. I don't really use `jQuery` so I'm not sure if `jQuery` adds methods to `NodeList` (I don't think they do) but even if they did they would overwrite the natively implentation of `NodeList` like take `.forEach` natively implemented and `jQuery` overwrite it, there's no problem with that, just like any other library that does that overwrites methods.

**Comment by eorroe** [comment]
I just think there hasn't been a good implementation of `NodeList`, I mean I've looked for other `NodeList` implementations and the only one I've seen is john resig's `NodeList.js` which is actually pretty good, but mine does generally the same thing but a bit more.

**Comment by simevidas** [comment]
There’s one more thing: The Elements methods (`query` and `queryAll`) use a different selection mechansim which fixes an [old issue of `querySelectorAll`](http://ejohn.org/blog/thoughts-on-queryselectorall/). (See [this discussion](https://twitter.com/simevidas/status/593592260865957888).) I think that’s one of the reasons the spec editors have decided to step away from NodeList. 

Note that the [spec mentions](http://www.w3.org/TR/2015/WD-dom-20150428/#nodelist) how it’s still uncertain if native Array methods in NodeList are possible:

> Warning! It is unclear if it will be possible to turn NodeList into an ArrayClass interface. Experimentation is planned by the Chromium project. 

From what I see, it doesn’t look good for NodeList, but the spec editors have more insight. (Most of them are on Twitter so you could ask for feedback.)

**Comment by eorroe** [comment]
Yes I saw the warning, but wouldn't that have to be fixed internally how `NodeList` work? And oh ok I see the problem with `querySelectorAll`. So they'll drop `NodeList` completely for that? Instead of fixing the internal work of `NodeList`? Why not fix `querSelectorAll` would that hurt compatability? 

And that's scary, I wouldn't know what to ask? What/how should I ask? Can you tweet at them a link to this discussion?

**Comment by simevidas** [comment]
The question is, is NodeList being deprecated and should work on this interface (like adding extensions) be avoided in the future. Hm, I can ask this question (either via a bug ticket or in the mailing list) tomorrow.

**Comment by eorroe** [comment]
Ok thanks.

**Comment by eorroe** [comment]
Closing because the upcoming `Elements` has been removed.

**Comment by simevidas** [comment]
\* postponed
