### ISSUE TITLE
Firefox Bug - textContent

### ISSUE THREAD

**Issue by kotgakapainor** [eorroe/NodeList.js#7]
I have trouble getting this code working in firefox. In chrome it works like a charm.
I'm fairly new to Jquery and have no idea how to solve the problem.

``` JS
$$(".edit").addEventListener("input", function() {
  var content = this.innerHTML;
  $$(".edit").set('textContent', content)
});
```

Here is a jsfiddle which works in chrome but not in firefox: http://jsfiddle.net/7mf8zfmb/

kind regards

**Comment by eorroe** [comment]
Hey thanks for trying out my library, so what happens is FF and chrome are adding different html when using `contenteditable` attribute, so use `textContent` instead of `innerHTML` here's some better code:

``` JS
var edits = $$('.edit');
edits.addEventListener("input", function() {
    var content = this.textContent;
    (edits[0] === this ? edits[1] : edits[0]).textContent = content;
});

```

Notice the `(edits[0] === this ? edits[1] : edits[0])` FF for some reason when doing `edits.set('textConent', content)` my lib is looping through each element, when setting `textContent`/`innerHTML` in FF it ends up blurring the focused element, and putting the cursor to the front, so instead of setting the `textContent` you're already typing in, only set the other.

**Also if you're using jQuery why use my library, why not just use one of them?**

**Comment by kotgakapainor** [comment]
Thank you very much for your input!
I'm using your library because I failed doing the same in jquery. Clearly my field of expertise is not that of a programmer but rather that of a designer. Therefore, I'm very thankful for any help.

Here is the final code for more than two edits:

``` JS
var edits = $$('.edit');
edits.addEventListener("input", function() {
    var content = this.textContent;
    var thisid = this.id;
    var filtered = edits.filter(function(div){return !div.matches('#'+thisid)});
 filtered.textContent = content;  
});
```

**Comment by eorroe** [comment]
Here's some better code, so you don't have to filter or check properties:

**Avoiding the use of `this` as well**

``` JS
var edits = $$('.edit');
edits.addEventListener("input", function(evt) {
    var content = evt.currentTarget.textContent;
    edits.forEach(function(div) {
      if(div !== evt.currentTarget) div.textContent = content;
    });
});
```
