### ISSUE TITLE
Add parent selector?

### ISSUE THREAD

**Issue by garrettw** [eorroe/NodeList.js#8]
One thing I have really found useful in jQuery is the parent selector – it lets me target only nodes that have a certain child node. jQuery has multiple ways of doing this, but the one I use, and the one that would probably be easiest to implement, is `.has()`. (see https://api.jquery.com/has/ )

Is there any possibility something like that could be added?

**Comment by eorroe** [comment]
The thing is I don't want to start creating my own methods, because then at the end I'd end up making another jQuery. But you can always make your own methods:

``` JS
$$.NL.has = function(query) {
  return this.map(function(node) {
    return node.closest(query) || node.querySelectorAll(query);
  });
}
```

Idk which node the `has` method looks for first the `parent` or the `child` so you could just swap the `closest` and `querySelectorAll` for the order.

So as you can see this is not a core need, something that would be used a whole lot like `set` method, so I would not implement it

**But thanks for checking out the library**

**Comment by eorroe** [comment]
I don't make my own selector engine, I just use the native `document.querySelectorAll` method, and don't make my own methods unless its crucial like `set`, `get`, `call` now `item` wasn't crucial but its a method that the native `NodeLists` provides so I just put it, except its more useful

**Comment by garrettw** [comment]
Ok, cool. Thanks for the code, btw.

I was noticing that your lib is about the same size as Sizzle, which is what jQuery uses. What makes yours different from/better than Sizzle?

**Comment by eorroe** [comment]
I'm just using what the browser provides, I don't create or use a css selector engine besides what the browser provides which is `querySelectorAll` and that's it.
